{
    "update_id": 849022184,
    "message": {
        "message_id": 527,
        "from": {
            "id": 270623373,
            "is_bot": False,
            "first_name": "Kaium",
            "username": "amankaium",
            "language_code": "en",
        },
        "chat": {
            "id": 270623373,
            "first_name": "Kaium",
            "username": "amankaium",
            "type": "private",
        },
        "date": 1718771457,
        "sticker": {
            "width": 512,
            "height": 389,
            "emoji": "😏",
            "set_name": "Shitsshitsshitsshists",
            "is_animated": False,
            "is_video": False,
            "type": "regular",
            "thumbnail": {
                "file_id": "AAMCBAADGQEAAgIPZnJfAdlg-ylj1OScxEvEamWJSwIAAv0AA2uuXgkXIcA_CFk7TgEAB20AAzUE",
                "file_unique_id": "AQAD_QADa65eCXI",
                "file_size": 3618,
                "width": 128,
                "height": 97,
            },
            "thumb": {
                "file_id": "AAMCBAADGQEAAgIPZnJfAdlg-ylj1OScxEvEamWJSwIAAv0AA2uuXgkXIcA_CFk7TgEAB20AAzUE",
                "file_unique_id": "AQAD_QADa65eCXI",
                "file_size": 3618,
                "width": 128,
                "height": 97,
            },
            "file_id": "CAACAgQAAxkBAAICD2ZyXwHZYPspY9TknMRLxGpliUsCAAL9AANrrl4JFyHAPwhZO041BA",
            "file_unique_id": "AgAD_QADa65eCQ",
            "file_size": 24182,
        },
    },
}
